name:                beelzebub
version:             0.1.0.0
github:              "yourfin/beelzebub"
license:             BSD3
author:              "YourFin"
maintainer:          "d.junkpobox+git@gmail.com"
copyright:           "YourFin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yourfin/beelzebub#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- typed-process
- text
- unix
- directory >= 1.3 && < 2
- mtl >= 2.2 && < 3
- network >= 3.1 && < 4
- aeson >= 1.4 && < 2
- conduit-extra >= 1.3 && < 2
- conduit >= 1.3 && < 2

library:
  source-dirs: src

executables:
  beez:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beelzebub

tests:
  beelzebub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beelzebub
